[package]
name = "frequency_analysis_limits"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
log = "0.4.29"
env_logger = "0.11.9"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
indicatif = { version = "0.17.8", features = ["rayon"] }
csv = "1.4.0"
thiserror = "2.0.18"
serde_json = "1.0.149"
sha2 = "0.11.0-rc.5"
ndarray = { version = "0.17.2", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.11.0"
clap = { version = "4.5", features = ["derive"] }
plotters = "0.3.7"
good_lp = { version = "1.15.0", features = ["highs"] }
statrs = "0.18.0"
rustc-hash = "2.1.2"
mimalloc = "0.1.48"
nalgebra = "0.33.3"
geo = "0.32.0"
qhull = "0.4.0"

[dev-dependencies]
num-rational = "0.4"
tempfile = "3.27.0"


[lints.rust]
unsafe_code = "warn" # or "deny"

[lints.clippy]
pedantic = "warn"
unwrap_used = "warn"

